# Generated by Django 4.1rc1 on 2022-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="E'lon nomi")),
                ('photo', models.ImageField(upload_to='elon_images', verbose_name='Rasmi')),
                ('etype', models.CharField(choices=[('KM', "Ko'chmas mulk"), ('T', 'Transport'), ('I', 'Ish'), ('H', 'Hayvonlar'), ('UB', "Uy va Bog'")], max_length=2, verbose_name='Turi')),
                ('contact', models.CharField(max_length=13, verbose_name='Aloqa uchun')),
                ('additional_info', models.TextField(verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
