# Generated by Django 4.2.6 on 2023-10-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagon',
            name='poyezd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vagonlar', to='chipta.poyezd'),
            preserve_default=False,
        ),
    ]
