# Generated by Django 4.2.6 on 2023-10-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0003_vagon_narxi_alter_yonalish_davomiyligi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chipta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz', models.CharField(max_length=9, verbose_name='Tel raqami')),
                ('sotilgan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chipta.yonalish')),
            ],
        ),
    ]
