# Generated by Django 4.2.6 on 2023-10-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chipta', '0004_chipta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipta',
            name='vagon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mijoz', to='chipta.vagon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chipta',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mijoz', to='chipta.yonalish'),
        ),
    ]
