# Generated by Django 4.2.6 on 2023-11-08 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chipta', '0006_chipta_joy_raqami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipta',
            name='mijoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiptalar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yonalish',
            name='poyezd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalish', to='chipta.poyezd', verbose_name='Poyezd'),
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
